### PR TITLE
Add a new argument to ShinyDriver()

### PR DESCRIPTION
**Pull request by cosi1**
Hello @wch and @gaborcsardi,

thank you for this great framework! The only issue I've encountered is the inability to pass custom R options to the Shiny session launched by Shinytest. This small patch fixes the problem; would you consider merging it into your code?
Feel free to modify my PR!

Thanks,
Paweł

### CODE REVIEW

**Comment by akaever** [comment]
This would indeed be very useful. Current workaround is to use `Sys.setenv` and `Sys.getenv`.

**Comment by hadley** [comment]
Fixes #249

**Comment by hadley** [comment]
Ooops, doesn't actually set fix that problem.

@cosi1 it's been a long time since you submitted you PR, and we apologise for the lack of communication. But it's not obvious what problem you're trying to solve, so it would be better to start with an issue so we can discuss whether or not there are existing approach that might work for you.

**Comment by cosi1** [comment]
@hadley, thank you for getting back to me. In the meantime, we've moved to another tool for integration testing, but in case someone reports a similar issue:
This PR provided a patch that allowed users to pass their R options to the environment created by Shinytest – some apps take R env options as input, e.g., configuration settings.

**Pull request closed without merging**
