### PR TITLE
Sort second level keys. Forces `input`/`output`/`export` to be consistently ordered

### LINKED ISSUE #409: Difference in json file generation between devtools::test() and devtools::check()
Hi, thanks for this nice package.
I am working on a [shiny app](https://github.com/LamaTe/mlr3shiny) in form of a package which I normally test using shinytest combined with testthat.
I have a minimalistic shiny test (to investigate the error) consisting of a single screenshot right after starting the app through recordTest(). The test passes when running testApp(), devtools::test() etc. 

However, I ran into a weird error which only occurs when running devtools::check(), always failing the test:
The json file that is generated suddenly varies but not in terms of 'actual' values but in terms of ordering - i.e. certain inputs appear in a different order than the one of the recorded test. Hence, the test 'fails' and devtools::check() does not pass.

Attached, you can find the expected test and the current test json files - They only vary in their ordering of input values.
[expected_and_current_json.zip](https://github.com/rstudio/shinytest/files/7154139/expected_and_current_json.zip)

I am out of ideas as to what causes this behaviour - any hint/help is greatly appreciated! Thanks in advance!

### PR DESCRIPTION
**Pull request by schloerke**
Fixes #409

------------------------------

@LamaTe Could you try this branch out to see if it fixes your situation? Thank you!

```r
remotes::install_github("rstudio/shinytest#415")
```

### CODE REVIEW

**Comment by bersbersbers** [comment]
I have the same problem as #409. But after `remotes::install_github("rstudio/shinytest#415")`, my checks are not finishing any more:
```
> shinytest::testApp("inst/shiny")
Running some_check.R Error: lexical error: invalid char in json text.
                                       character(0)
                     (right here) ------^
```

The same is not happening following `remotes::install_github("rstudio/shinytest")`. I also double-checked
```bash
git clone https://github.com/rstudio/shinytest.git
cd shinytest
git checkout v1.5.1
git cherry-pick 2716b05 4bf6914
R -e "devtools::install()"
```
and the same thing is happening; next try,
```bash
git checkout v1.5.1
R -e "devtools::install()"
```
and tests are passing. So this PR seems to be missing some edge case.

**Comment by bersbersbers** [comment]
The above seems to be the same problem as in https://github.com/rstudio/shinytest/pull/415/checks?check_run_id=3680356347

**Comment by schloerke** [comment]
Thank you @bersbersbers ! Looking into it...

**Comment by schloerke** [comment]
Closing PR (as it is not a fix) and moving conversation back to #409

**Pull request closed without merging**
